#! /usr/bin/env python

import sys
import os
sys.path.append(os.getcwd() + '/src')

import BlueReconn

try:
    BlueReconn = BlueReconn.BlueReconn()
    BlueReconn.run()
except Exception as e:
    print("Error: %s" % str(e))
